name: Scrape Douyin Trending

on:
  schedule:
    - cron: '0 * * * *'   # chạy mỗi giờ; chỉnh theo bạn
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate package-lock.json if missing
        run: |
          if [ ! -f package-lock.json ]; then npm install; fi

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          DEBUG: 'true'                # bật debug (ghi file HTML/JSON)
          LIMIT: '20'
        run: |
          node crawler-github.js

      - name: Upload debug artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: douyin-debug
          path: debug/**/*
